export { default as HeroSection } from './HeroSection';
export { default as ServicesSection } from './ServicesSection';
export { default as AboutSection } from './AboutSection';
export { default as ProcessSection } from './ProcessSection';
export { default as StatsSection } from './StatsSection';
export { default as TestimonialsSection } from './TestimonialsSection';
export { default as ClientsSection } from './ClientsSection';
export { default as CTASection } from './CTASection';
export { default as ContactSection } from './ContactSection';
